spring:
  application:
    name: backend
  mail:
    host: smtp.naver.com
    port: 587
    username: "${SPRING_MAIL_USERNAME}"
    password: "${SPRING_MAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.naver.com
            protocols: TLSv1.2
  # ▲▲▲▲▲ 여기까지 수정 ▲▲▲▲▲
server:
  port: 8888

jwt:
  secret:
    key: a2F카오디오a2FkaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaQ==
  token:
    expiration-time: 3600000 # 1시간 (밀리초 단위)
