spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:63306/booking_db
    username: root
    password: 1234
  jpa:
    hibernate:
      #ddl option: none || validate || update | create | create-drop
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  
#JPA log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE